# Generated by Django 5.1.5 on 2025-02-24 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='files')),
                ('current_CTC', models.IntegerField(default=0)),
                ('expected_CTC', models.IntegerField(default=0)),
                ('interview_date', models.TextField()),
                ('apply_status', models.CharField(default='pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.jobpost')),
            ],
        ),
    ]
