# Generated by Django 5.1.5 on 2025-02-27 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0003_alter_jobapply_job_alter_jobapply_user_myjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.jobpost'),
        ),
    ]
