# Generated by Django 5.1.5 on 2025-02-27 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_jobapply_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myjobs',
        ),
    ]
