# Generated by Django 5.1.5 on 2025-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('vaccancy', models.IntegerField(default=0)),
                ('published', models.DateField(auto_now=True)),
                ('experience', models.CharField(default='', max_length=20)),
                ('salary', models.IntegerField(default=0)),
                ('application_deadline', models.DateField(auto_now=True)),
                ('description', models.TextField()),
                ('company', models.CharField(max_length=50)),
                ('tagline', models.CharField(max_length=30)),
                ('companydesc', models.TextField()),
                ('website', models.CharField(max_length=30)),
                ('facebook', models.CharField(max_length=30)),
                ('twitter', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
